/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-vision.h
 #	source generated by 4D Plugin Wizard
 #	Project : vision
 #	author : miyako
 #	2020/12/31
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_VISION_H
#define PLUGIN_VISION_H

#include "4DPluginAPI.h"

#include <vector>
#include <Cocoa/Cocoa.h>
#include <Vision/Vision.h>

#include "4DPlugin-JSON.h"

#pragma mark -

void vision_process_data(PA_PluginParameters params);
void vision_get_version(PA_PluginParameters params);

#endif /* PLUGIN_VISION_H */
